### ISSUE TITLE
Add better validation for .mp4 video mode

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/gopro2gsv#29]
Currently there is limited validation for .mp4 files

https://github.com/trek-view/gopro2gsv#validation-1

With introduction of new modes (e.g. #28 ) validation should be stricter

* file extension must be `.mp4`
* filenames must start with `GS` or `VIDEO_`
* `XMP-GSpherical:ProjectionType` is `equirectangular`
* `trackN:MetaFormat` is `gpmd`
* `trackN:GPSDateTime` has more than 10 entries

Where `trackN` is the track that contains the gpmd telemetry.

**Comment by fqrious** [comment]
does this mean `.mp4` mode should continue to use `video->video` pipeline and only `.360` mode goes through `video->image->video` piepliine?
