### ISSUE TITLE
User should be able to set --size_of_nadir as percentage of image height in all modes

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/gopro2gsv#35]
User can enter whole numbers between 5 and 30.

`--path_to_nadir` must also be supplied.

**Comment by fqrious** [comment]
done

**Comment by himynamesdave** [comment]
@fqrious 

When user does not set a `size_of_nadir`, the default value used should be 25 if `path_to_nadir` is passed.

### No frame extraction, add a nadir with default size (25%) -- currently issue as nadir covers 100% of image

```shell
python3 gopro2gsv.py \
	--input_video tests/ski/GS016843.mp4 \
	--path_to_nadir stock_nadirs/without_gopro/trek_view_full_nadir.png \
	--output_filepath tests/output/mode1/test1/GS016843.mp4
```

### No frame extraction, add a nadir with custom size (10%) -- works as expected

```shell
python3 gopro2gsv.py \
	--input_video tests/ski/GS016843.mp4 \
	--path_to_nadir stock_nadirs/without_gopro/trek_view_full_nadir.png \
	--size_of_nadir 10 \
	--output_filepath tests/output/mode1/test2/GS016843.mp4
```

**Comment by fqrious** [comment]
fixed
