### ISSUE TITLE
Max video length input not being adhered to

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/gopro2gsv#36]
#27 this mode does not seem to work as expected.

Trying this test

### Extract frames from video input at 0.5 FPS and rebuild video with 20 second max (100 frames)

```shell
python3 gopro2gsv.py \
	--input_video tests/ski/GS016843.mp4 \
	--path_to_nadir stock_nadirs/without_gopro/trek_view_full_nadir.png \
	--extract_fps 2 \
	--max_output_video_secs 20 \
	--output_filepath tests/output/test3/GS016843.mp4
```

187 * 2 = 374 frames = 375 / 5 = 75 seconds final output. Thus expect 4 videos output.

However, only one video is produced with length of 00:01:15.

**Comment by fqrious** [comment]
done
