### ISSUE TITLE
validation for mode 1 are not being checked

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/gopro2gsv#37]
#29 

```shell
python3 gopro2gsv.py \
	--input_video tests/hero_videos/GH018678.MP4 \
	--path_to_nadir stock_nadirs/without_gopro/trek_view_full_nadir.png \
	--output_filepath tests/output/test0/GH018678.MP4
```

To try and make this easier for the script we should also add a flag where user sets mode at input 

* `--mode` = https://github.com/trek-view/gopro2gsv/tree/max-dev#gopro2gsv

https://github.com/trek-view/gopro2gsv/blob/max-dev/design/mvp/modes-specification.md

**Comment by fqrious** [comment]
I don't think mode is needed
