### ISSUE TITLE
detail ffmpeg command for .360 mode

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/gopro2gsv#48]
as per this comment

https://github.com/trek-view/gopro2gsv/issues/45#issuecomment-1833315354

**Comment by fqrious** [comment]
`ffmpeg -i VIDEO.360 -r EXTRACT_FPS -filter_complex '[0:v:0][0:v:1]vstack=inputs=2,v360=eac:equirect[out]' -map '[out]' OUTPUT_PATH/_processing/FRAME-%05d.jpg`
