### ISSUE TITLE
Mode 1 (video->video without frames) should print GPX in the same way it does for other modes too.

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/gopro2gsv#49]
Note, unlike the frame -> video gpx files, this one is produced from the actual video, not the frames

https://github.com/trek-view/gopro2gsv/blob/max-dev/design/mvp/modes-specification.md#1d-output

**Comment by fqrious** [comment]
`gpx` files general by `exiftool` does not show all gps points, it only shows gps points that have `timestamp`

**Comment by himynamesdave** [comment]
@fqrious yes, that's fine. I will make a note of that

This is only for videos create in mode 1, video->video
