### ISSUE TITLE
For modes 2/3/4 add following to ffmpeg command

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/gopro2gsv#56]
```
-pix_fmt yuv420p10le -c:v libx265 -preset slow -tune stillimage -crf 28
```

**Comment by fqrious** [comment]
![image](https://github.com/trek-view/gopro2gsv/assets/29603874/3a08ec09-5e64-4d6a-ad46-0b5018881855)

if you remove `-preset slow -tune stillimage`, it works

**Comment by fqrious** [comment]
I think stillimage is only supported by h.264 and not h.265
